### ISSUE TITLE
Public Karman Docker Image

### ISSUE THREAD

**Issue by kenowi-dev** [Karaoke-Manager/karman#55]
# Request
Request to make the docker image for the Karman server public. 

# Implications
Currently it is only accessible for internal members of the "Karaoke-Manager" Group. 
Since the Repository is public anyway, no additional data would be publicised.

# Reason
A public image would make the development for API-dependent applications (e.g. Karman Web) easier, since the server can be started directly from an already build image.

**Comment by codello** [comment]
The image should now be publicly available.
